<a href="https://colab.research.google.com/github/kanikaKanu90/notebook/blob/master/Preprocessing_And_Sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

col_range = [i for i in range(0,28)]
df = pd.read_csv("/content/sample_data/covid19_cases_switzerland_openzh-phase2.csv", usecols= col_range)

df.head()

         Date   AG   AI   AR   BE   BL  ...   UR   VD   VS   ZG    ZH    CH
0  2020-05-31  0.0  NaN  NaN  0.0  0.0  ...  0.0  0.0  0.0  0.0   0.0   0.0
1  2020-06-01  0.0  NaN  NaN  0.0  1.0  ...  0.0  0.0  1.0  0.0   0.0   3.0
2  2020-06-02  0.0  NaN  0.0  1.0  1.0  ...  0.0  4.0  2.0  0.0   2.0  20.0
3  2020-06-03  1.0  0.0  0.0  2.0  2.0  ...  NaN  6.0  2.0  0.0   5.0  38.0
4  2020-06-04  3.0  NaN  0.0  4.0  2.0  ...  NaN  9.0  4.0  0.0  13.0  62.0

[5 rows x 28 columns]

In [5]:
df.set_index(['Date'],inplace=True) # set index
df[0:1] = 0 #initialize first row with zero

In [6]:
df.shape

(148, 27)

In [7]:
df.drop(columns=['CH'],inplace=True, axis=1)
df.shape

(148, 26)

In [8]:
df.head()

             AG   AI   AR   BE   BL   BS  ...   TI   UR   VD   VS   ZG    ZH
Date                                      ...
2020-05-31  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   0.0
2020-06-01  0.0  NaN  NaN  0.0  1.0  0.0  ...  0.0  0.0  0.0  1.0  0.0   0.0
2020-06-02  0.0  NaN  0.0  1.0  1.0  0.0  ...  0.0  0.0  4.0  2.0  0.0   2.0
2020-06-03  1.0  0.0  0.0  2.0  2.0  1.0  ...  0.0  NaN  6.0  2.0  0.0   5.0
2020-06-04  3.0  NaN  0.0  4.0  2.0  1.0  ...  1.0  NaN  9.0  4.0  0.0  13.0

[5 rows x 26 columns]

In [9]:
np.isnan(df).sum()
df.shape

(148, 26)

In [ ]:
def fill_missing(df):
    for row in range(df.shape[0]):
        for col in range(df.shape[1]):
            if np.isnan(df[row, col]):
                df[row, col] = df[row-1, col]        

fill_missing(df.values)

np.isnan(df).sum()

In [11]:
df.to_csv('/content/sample_data/exported.csv', index = True)

In [12]:
daily_changes_df = pd.DataFrame()

def calculate_daily_changes(data_toBe_treated):
  for row in range(data_toBe_treated.shape[0]):
    for col in range(data_toBe_treated.shape[1]):
      daily_changes_df.loc[row, col] = data_toBe_treated[row, col] - data_toBe_treated[row-1, col]


calculate_daily_changes(df.values)

daily_changes_df.fillna(0)
daily_changes_df[0:1] = 0.0

         0      1      2       3   ...       22      23      24       25
0   -3516.0 -197.0 -382.0 -7646.0  ... -12601.0 -4868.0 -1010.0 -11877.0
1       0.0    0.0    0.0     0.0  ...      0.0     1.0     0.0      0.0
2       0.0    0.0    0.0     1.0  ...      4.0     1.0     0.0      2.0
3       1.0    0.0    0.0     1.0  ...      2.0     0.0     0.0      3.0
4       2.0    0.0    0.0     2.0  ...      3.0     2.0     0.0      8.0
..      ...    ...    ...     ...  ...      ...     ...     ...      ...
143   272.0   23.0   28.0   512.0  ...    784.0   363.0    61.0    987.0
144   266.0   18.0   26.0   552.0  ...    792.0    33.0    74.0    781.0
145     0.0   15.0   52.0   802.0  ...    744.0     0.0    63.0    655.0
146     0.0   10.0    0.0   715.0  ...      0.0     0.0     0.0      0.0
147     0.0    0.0    0.0   534.0  ...      0.0     0.0     0.0      0.0

[148 rows x 26 columns]

In [13]:
daily_changes_df.to_csv('/content/sample_data/changes_daily.csv', index = True)

In [14]:
dnc_avg = daily_changes_df.rolling(3)
dnc_avg

Rolling [window=3,center=False,axis=0]

In [15]:
cantons = df.columns
date = df.index

cantons, date

(Index(['AG', 'AI', 'AR', 'BE', 'BL', 'BS', 'FR', 'GE', 'GL', 'GR', 'JU', 'LU',
        'NE', 'NW', 'OW', 'SG', 'SH', 'SO', 'SZ', 'TG', 'TI', 'UR', 'VD', 'VS',
        'ZG', 'ZH'],
       dtype='object'),
 Index(['2020-05-31', '2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04',
        '2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08', '2020-06-09',
        ...
        '2020-10-16', '2020-10-17', '2020-10-18', '2020-10-19', '2020-10-20',
        '2020-10-21', '2020-10-22', '2020-10-23', '2020-10-24', '2020-10-25'],
       dtype='object', name='Date', length=148))

In [52]:

# import pandas as pd
# from bokeh.models import ColumnDataSource
# from bokeh.palettes import all_palettes
# from bokeh.plotting import figure, output_file, show

# data = {'day': [2, 2, 2, 3, 3, 3, 5, 5, 5], 'id': ['catx', 'kagm', 'dyrt', 'catx', 'kagm', 'dyrt', 'catx', 'kagm', 'dyrt'], 'cnt': [4, 3, 5, 3, 3, 4, 2, 2, 2]}
# df = pd.DataFrame.from_dict(data)

# output_file('plot.html')
# tooltips = [
#     ("day", "@day"),
#     ("id", "@$name"),
#     ("count", "@cnt")]
# p = figure(tooltips=tooltips, plot_width=800, plot_height=800)

# sources = []
# colors = all_palettes['Viridis'][len(set(df['id'].tolist()))]
# pd.options.mode.chained_assignment = None #Supress false positive warning
# for ID, color in zip(set(df['id'].tolist()), colors):
#     dfSubset = df.loc[df['id'] == ID]
#     dfSubset['color'] = color
#     sources.append(ColumnDataSource(dfSubset))
#     p.circle(x = 'day', y = 'cnt', legend = 'id', color = 'color', name = 'id', alpha = 0.5, size = 15, source = sources[-1])

# p.legend.click_policy="hide"

# show(p)

In [ ]:
# # Create a color list to represent different cantons in the plot, you can either construct your own color patette or use the Bokeh color pallete
# color_palette = ...

# # Build a dictionary with date and each canton name as a key, i.e., {'date':[], 'AG':[], ..., 'ZH':[]}
# # For each canton, the value is a list containing the averaged daily new cases
# source_dict = ...

# source = ColumnDataSource(data=source_dict)

# ### Task 2: Data Visualization

# ## T2.1: Draw a group of lines, each line represents a canton, using date, dnc_avg as x,y. Add proper legend.
# # https://docs.bokeh.org/en/latest/docs/reference/models/glyphs/line.html?highlight=line#bokeh.models.glyphs.Line
# # https://docs.bokeh.org/en/latest/docs/user_guide/interaction/legends.html

# p = figure(plot_width=1000, plot_height=800, x_axis_type="datetime")
# p.title.text = 'Daily New Cases in Switzerland'

# lines = []
# for canton,color in zip(cantons,color_palette): 
# 	lines.append(...)

# # Make the legend of the plot clickable, and set the click_policy to be "hide"
# ## T2.2 Add hovering tooltips to display date, canton and averaged daily new case

# # (Hovertip doc) https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#hovertool
# # (Date hover)https://stackoverflow.com/questions/41380824/python-bokeh-hover-date-time
# hover = ...

# p.add_tools(hover)

# show(p)
# output_file("dvc_ex2.html")
# save(p)

In [58]:
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColumnDataSource
from bokeh.models.tools import HoverTool

from bokeh.palettes import Spectral5
from bokeh.transform import factor_cmap

output_file('cases_by_date.html')

grouped = df.groupby('Date')['AG', 'AI', 'AR', 'BE', 'BL', 'BS', 'FR', 'GE', 'GL', 'GR',
        'VS_pc', 'VS_diff_pc', 'ZG_diff', 'ZG_pc', 'ZG_diff_pc', 'ZH_diff',
        'ZH_pc', 'ZH_diff_pc', 'CH_diff', 'CH_pc'].sum()

print(grouped)        

source = ColumnDataSource(grouped)
cantons = source.data['Date'].tolist()
p = figure(x_range=cantons) #figure(x_axis_type="datetime")

color_map = factor_cmap(field_name='Date',
                    palette=Spectral5, factors=cantons)

p.vbar(x='Date', top='AG', source=source, width=0.70, color=color_map)

p.title.text ='Cases as per Canton'
p.xaxis.axis_label = 'Canton'
p.yaxis.axis_label = 'Date'

hover = HoverTool()
hover.tooltips = [
    ("Totals", "@AG / @AI / @AR")]

hover.mode = 'vline'

p.add_tools(hover)

show(p)

                AG     AI     AR  ...  ZH_diff_pc  CH_diff     CH_pc
Date                              ...
2020-05-31     0.0    0.0    0.0  ...    0.000000      0.0  0.000000
2020-06-01     0.0    0.0    0.0  ...    0.000000      3.0  0.000002
2020-06-02     0.0    0.0    0.0  ...    0.000001     17.0  0.000013
2020-06-03     1.0    0.0    0.0  ...    0.000002     18.0  0.000025
2020-06-04     3.0    0.0    0.0  ...    0.000005     24.0  0.000041
...            ...    ...    ...  ...         ...      ...       ...
2020-10-21  3250.0  154.0  304.0  ...    0.000649   5214.0  0.041833
2020-10-22  3516.0  172.0  330.0  ...    0.000513   4590.0  0.044850
2020-10-23  3516.0  187.0  382.0  ...    0.000431   3938.0  0.047440
2020-10-24  3516.0  197.0  382.0  ...    0.000431   1910.0  0.048695
2020-10-25  3516.0  197.0  382.0  ...    0.000431    871.0  0.049268

[148 rows x 20 columns]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/bokeh/models/mappers.py:147: UserWarning: Palette length does not match number of factors. ['2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08', '2020-06-09', '2020-06-10', '2020-06-11', '2020-06-12', '2020-06-13', '2020-06-14', '2020-06-15', '2020-06-16', '2020-06-17', '2020-06-18', '2020-06-19', '2020-06-20', '2020-06-21', '2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25', '2020-06-26', '2020-06-27', '2020-06-28', '2020-06-29', '2020-06-30', '2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04', '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08', '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12', '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16', '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20', '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24', '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28', '2020-07-29', '2020-07-30', '2020-07-31', '2020-08-01', '2020-08-02', '2020-08-03', '2020-08-04', '2020-08-05', '2020-08-06', '2020-08-07', '2020-08-08', '2020-08-09', '2020-08-10', '2020-08-11', '2020-08-12', '2020-08-13', '2020-08-14', '2020-08-15', '2020-08-16', '2020-08-17', '2020-08-18', '2020-08-19', '2020-08-20', '2020-08-21', '2020-08-22', '2020-08-23', '2020-08-24', '2020-08-25', '2020-08-26', '2020-08-27', '2020-08-28', '2020-08-29', '2020-08-30', '2020-08-31', '2020-09-01', '2020-09-02', '2020-09-03', '2020-09-04', '2020-09-05', '2020-09-06', '2020-09-07', '2020-09-08', '2020-09-09', '2020-09-10', '2020-09-11', '2020-09-12', '2020-09-13', '2020-09-14', '2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18', '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22', '2020-09-23', '2020-09-24', '2020-09-25', '2020-09-26', '2020-09-27', '2020-09-28', '2020-09-29', '2020-09-30', '2020-10-01', '2020-10-02', '2020-10-03', '2020-10-04', '2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08', '2020-10-09', '2020-10-10', '2020-10-11', '2020-10-12', '2020-10-13', '2020-10-14', '2020-10-15', '2020-10-16', '2020-10-17', '2020-10-18', '2020-10-19', '2020-10-20', '2020-10-21', '2020-10-22', '2020-10-23', '2020-10-24', '2020-10-25'] will be assigned to `nan_color` gray
  warnings.warn("Palette length does not match number of factors. %s will be assigned to `nan_color` %s" % (extra_factors, self.nan_color))